import { ShardingStrategy } from '../sharding-strategy.interface';

/**
 * Hash-based sharding: `hash(key) % shardCount`.
 *
 * Oja's userId is a UUID (`crypto.randomUUID()`), generated by the app at
 * registration time before any row exists anywhere - there is no
 * auto-increment sequence to shard by, and a shared sequence would itself
 * be a single point of contention across 3 independent databases. Hashing
 * the UUID string distributes users evenly regardless of when they signed
 * up, unlike range sharding, which would pile every *new* signup onto
 * whichever shard currently owns the top of the range (a "hot" shard).
 *
 * djb2 is not cryptographic - it's chosen because it's simple, fast, and
 * deterministic across processes, which is exactly what's needed here: the
 * same userId must always resolve to the same shard, on every replica,
 * forever (until a deliberate resharding operation, which this demo does
 * not implement).
 */
export class HashShardingStrategy implements ShardingStrategy {
  readonly name = 'hash';

  constructor(readonly shardCount: number) {
    if (shardCount < 1) {
      throw new Error('shardCount must be >= 1');
    }
  }

  resolveShard(key: string | number): number {
    const numericKey = typeof key === 'number' ? key : this.djb2(key);
    return this.mod(numericKey, this.shardCount);
  }

  private djb2(input: string): number {
    let hash = 5381;
    for (let i = 0; i < input.length; i++) {
      hash = (hash * 33) ^ input.charCodeAt(i);
    }
    // >>> 0 forces an unsigned 32-bit integer.
    return hash >>> 0;
  }

  /** JS's `%` can return negative results for negative operands; normalize. */
  private mod(value: number, divisor: number): number {
    return ((value % divisor) + divisor) % divisor;
  }
}
